-- formated sql

-- changeset dubrovsky:1
CREATE TABLE "users" (
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    PHONE VARCHAR(255),
    ROLE VARCHAR(255) NOT NULL,
    IMAGE BYTEA
)